### ISSUE TITLE
understanding variable names

### ISSUE THREAD

**Issue by PhilippLee** [Hanjun-Dai/graph_comb_opt#1]
In code/s2v_mvc/mvc_lib/src/lib/qnet.cpp, line 66, what is the "aux_input" used to do? And in code/s2v_mvc/mvc_lib/include/config.h, what are "cfg::reg_hidden" and "cfg::aux_dim" used to indicate?

**Comment by Hanjun-Dai** [comment]
**aux_input**: one can add some auxiliary information to the node representation. For example, in MVC, one can add the degree of node as auxiliary information. 

**cfg::aux_dim**: global variable. This tells the dimensionality of auxiliary information. 

 **cfg::reg_hidden**: if it is not zero, then the Q function is computed via a 2-layer NN on top of the graph embedding, where reg_hidden equals to dimension of hidden layer; if it is zero, then the linear regression is used.

**Comment by Hanjun-Dai** [comment]
Feel free to reopen the issue if you have further questions on this topic.
