### ISSUE TITLE
Data generator for TSP?

### ISSUE THREAD

**Issue by xzymustbexzy** [Hanjun-Dai/graph_comb_opt#17]
Hello, I'm going to run `s2v_tsp2d`. However, I didn't find data generator for TSP problem. So the program cannot run without data file. Is that my mistake? 
![image](https://user-images.githubusercontent.com/29947288/69116188-60ad6480-0ac6-11ea-8b80-101f36bf4d2c.png)

![image](https://user-images.githubusercontent.com/29947288/69116154-44112c80-0ac6-11ea-82d5-5632eed7f597.png)

**Comment by Hanjun-Dai** [comment]
Hi,

The data is available via the dropbox link (in README).
You need to download the data and put it in the path specified above.

**Comment by xzymustbexzy** [comment]
Thank you!!! I ran the program successfully.  

But I found something confused. I write my own data generator for tsp2d according to your data.  And I set n=10, which means min-n = 10 and max-n = 10.   
The average cost converged on `2.72275822993`. 
![image](https://user-images.githubusercontent.com/29947288/70523970-22640c00-1b7f-11ea-8f7c-a7db7d9b8818.png)

However, the precise answer given by my dynamic programming algorithm is `2.899085780099285`.  

It is weird that I got a cost lower than the standard answer. Is it possible that your program have missed adding the cost of the route back to starting point? Because I try to print the process of cost accumulation. I found there are only 9 times addition.
![image](https://user-images.githubusercontent.com/29947288/70524699-b2ef1c00-1b80-11ea-8435-b665608a629a.png)
I'am trying to fix it but I don't know how to start. Can you give me some suggestions? Thank you!

**Comment by Hanjun-Dai** [comment]
Hi, 

The cost printed at each step is the 'delta' between new tour length and old tour length. Our algorithm will also produce the actual solution. You can double check the tour length of the solution to verify.

**Comment by Sword-holder** [comment]
Ok, I understand. Thanks for your answer.

**Comment by xzymustbexzy** [comment]
> Hi,
> 
> The cost printed at each step is the 'delta' between new tour length and old tour length. Our algorithm will also produce the actual solution. You can double check the tour length of the solution to verify.

Ok, I understand. Thanks for your answer.
