### ISSUE TITLE
Can't run s2v_mvc

### ISSUE THREAD

**Issue by ariewahyu** [Hanjun-Dai/graph_comb_opt#2]
I run the training, `run_nstep_dqn.sh` of s2v_mvc and got this error:
`File "main.py", line 77, in <module>
    api = MvcLib(sys.argv)
  File "/home/abcd/S2V-DQN/code/s2v_mvc/mvc_lib/mvc_lib.py", line 11, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libmvc.so' % dir_path)
  File "/home/abcd/anaconda2/envs/tensorflow-gpu/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/abcd/S2V-DQN/code/s2v_mvc/mvc_lib/build/dll/libmvc.so: undefined symbol: _ZTVN3fmt11FormatErrorE`

**Comment by Hanjun-Dai** [comment]
Hi, you need to compile with position independent mode of libfmt. 

To do so, open the CMakeLists.txt under the root folder of libfmt, and add a line 
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)`
into the file. 

Then recompile and reinstall limfmt
