### ISSUE TITLE
MaxCut loss always 0

### ISSUE THREAD

**Issue by abhishekm71** [Hanjun-Dai/graph_comb_opt#25]
Hi, 
Thanks for the code. I am trying to run the MaxCut algorithm, but it seems that the loss is always 0. Any idea what could be going wrong?
Thanks

**Comment by Hanjun-Dai** [comment]
Hi, are you using py2 or 3?
The division behavior is different in py3 and py3

**Comment by abhishekm71** [comment]
Thanks a lot for replying.
Yes, I was using the incorrect python version.
