### ISSUE TITLE
Is discount factor wrongly implemented?

### ISSUE THREAD

**Issue by yongwonshin** [Hanjun-Dai/graph_comb_opt#26]
Hello, I have a question about the decay factor (discount factor) in N-step DQN (paper & implementation)
I found the following equation in the paper(page 6; first paragraph):
![image](https://user-images.githubusercontent.com/20634731/90412424-0cccbc00-e0e8-11ea-975f-edef9d15e911.png)
As far as I know, discount factor should be applied as following:
![image](https://user-images.githubusercontent.com/20634731/90412733-6f25bc80-e0e8-11ea-9224-75f70bd65a39.png)
I checked the implementation of tsp2d(code/s2v_tsp2d/tsp2d_lib/src/tsp2d_lib.cpp), and in the `Fit()` function, former version of equation is implemented.
```c++
double Fit(const double lr)
{
    NStepReplayMem::Sampling(cfg::batch_size, sample);
    bool ness = false;
    for (int i = 0; i < cfg::batch_size; ++i)
        if (!sample.list_term[i])
        {
            ness = true;
            break;
        }
    if (ness)
        PredictWithSnapshot(sample.g_list, sample.list_s_primes, list_pred);
    
    list_target.resize(cfg::batch_size);
    for (int i = 0; i < cfg::batch_size; ++i)
    {
        double q_rhs = 0;
        if (!sample.list_term[i])
            q_rhs = cfg::decay * max(sample.g_list[i]->num_nodes, list_pred[i]->data());
        q_rhs += sample.list_rt[i];
        list_target[i] = q_rhs;
    }

    return Fit(lr, sample.g_list, sample.list_st, sample.list_at, list_target);
}
```

I'm currently studying the DRL, so I might be wrong... But since I couldn't also found the reason why you used discount factor in that way, I write this issue.
Thank you for providing nice implementation! I've really learned a lot from it!

**Comment by Hanjun-Dai** [comment]
Hi, 

you are correct about the equation. But in our paper we mostly use one-step unrolling of bellman equation, and set the discounting factor to be 1. So it doesn't really matter.
