### ISSUE TITLE
Are there some tricks not mentioned in the paper?

### ISSUE THREAD

**Issue by ZhangZiYang11** [Hanjun-Dai/graph_comb_opt#33]
Hi, thank you for the code. I try to rewrite these codes with tensorflow according to the paper, but fail to find a right answer. May I ask if there are some tricks not mentioned in the paper? 
Sorry for my slow-witted question, but I can barely read C++ codes

**Comment by Dicer98k** [comment]
I also have a similar issue. Recently, I've been considering applying this model to a biological problem, and I need to rewrite the code using TensorFlow too. Currently, I'm referring to a similar work - GCOMB, which was implemented using TensorFlow 1.8.0. Perhaps this could be helpful for you.

**Comment by ZhangZiYang11** [comment]
> I also have a similar issue. Recently, I've been considering applying this model to a biological problem, and I need to rewrite the code using TensorFlow too. Currently, I'm referring to a similar work - GCOMB, which was implemented using TensorFlow 1.8.0. Perhaps this could be helpful for you.

Hi, according to previous issues of this project, there are indeed some detailed tricks.(https://github.com/Hanjun-Dai/graph_comb_opt/issues/15#issue-464806463),  (https://github.com/Hanjun-Dai/graph_comb_opt/issues/21#issue-598631474).
With these tricks and the basic frame of the paper, I've reimplemented successfully. Hope these could be helpful for you.

**Comment by Dicer98k** [comment]
Thank you for your help. By the way, would you like to open-source your code on GitHub, so that TensorFlow beginners like me and others with needs can reference it ？Orz

**Comment by ZhangZiYang11** [comment]
> Thank you for your help. By the way, would you like to open-source your code on GitHub, so that TensorFlow beginners like me and others with needs can reference it ？Orz

I have uploaded my code to (https://github.com/ZhangZiYang11/tensorflow-implement-of-Learning-Combinatorial-Optimization-Algorithms-over-Graphs.git). Hope this could be helpful for you.
