### ISSUE TITLE
Data for TSP is unreadable

### ISSUE THREAD

**Issue by Azulgrana1** [Hanjun-Dai/graph_comb_opt#5]
Hi Hanjun,
I downloaded the synthetic data for TSP from the Dropbox link you provided. However, the content in the .gz file is unreadable. It is neither a folder, nor a file of any know extension. I wonder if there is something wrong with the file, or there is a special way to extract it. 

Thanks a lot!
Yuhan

**Comment by Hanjun-Dai** [comment]
Hi there, 

I've tested  under Ubuntu 16.04, using the following command:
`tar -zxvf test_tsp2d.gz`

Now I've renamed the file extensions to 'tar.gz', so the GUI version (e.g., archive manager in ubuntu) should also work. 

Let me know if there's any problem with the files.

**Comment by Azulgrana1** [comment]
It worked. Thank you very much!
