### ISSUE TITLE
Building graphNN

### ISSUE THREAD

**Issue by jasontlam** [Hanjun-Dai/graph_comb_opt#7]
Hello,

When I try to build the graphNN library I get this error. 

make: *** No rule to make target `build_cpuonly/objs/cxx/src//nn/hit_at_k.o', needed by `build_cpuonly/lib/libgnn.a'.  Stop.

Thanks!

**Comment by jasontlam** [comment]
needed to brew install findutils for macOS

**Comment by jasontlam** [comment]
When I try and build the dynamic library for realworld_s2v_tsp2d I get the error below.  Do you have any ideas how to fix this ?
Thanks! 

Undefined symbols for architecture x86_64:
  "gnn::ConcatCols<gnn::GPU, float>::ConcatCols(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::ConcatCols<gnn::GPU, float> > std::__1::shared_ptr<gnn::ConcatCols<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
  "gnn::ElewiseAdd<gnn::GPU, float>::Forward(std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, gnn::Phase)", referenced from:
      vtable for gnn::ElewiseAdd<gnn::GPU, float> in qnet.o
  "gnn::ElewiseAdd<gnn::GPU, float>::Backward(std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, std::__1::vector<bool, std::__1::allocator<bool> >&, std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&)", referenced from:
      vtable for gnn::ElewiseAdd<gnn::GPU, float> in qnet.o
  "gnn::ElewiseAdd<gnn::GPU, float>::ElewiseAdd(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<float, std::__1::allocator<float> >, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::ElewiseAdd<gnn::GPU, float> > std::__1::shared_ptr<gnn::ElewiseAdd<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::ReduceMean<gnn::GPU, float>::ReduceMean(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, bool, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::ReduceMean<gnn::GPU, float> > std::__1::shared_ptr<gnn::ReduceMean<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::ReduceMean<gnn::GPU, float> > std::__1::shared_ptr<gnn::ReduceMean<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::MultiMatMul<gnn::GPU, float>::MultiMatMul(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::MultiMatMul<gnn::GPU, float> > std::__1::shared_ptr<gnn::MultiMatMul<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::SquareError<gnn::GPU, float>::Forward(std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, gnn::Phase)", referenced from:
      vtable for gnn::SquareError<gnn::GPU, float> in old_qnet.o
      vtable for gnn::SquareError<gnn::GPU, float> in qnet.o
  "gnn::SquareError<gnn::GPU, float>::Backward(std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, std::__1::vector<bool, std::__1::allocator<bool> >&, std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&)", referenced from:
      vtable for gnn::SquareError<gnn::GPU, float> in old_qnet.o
      vtable for gnn::SquareError<gnn::GPU, float> in qnet.o
  "gnn::SquareError<gnn::GPU, float>::SquareError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::SquareError<gnn::GPU, float> > std::__1::shared_ptr<gnn::SquareError<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::SquareError<gnn::GPU, float> > std::__1::shared_ptr<gnn::SquareError<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::AdamOptimizer<gnn::GPU, float>::AdamOptimizer(gnn::ParamSet<gnn::GPU, float>*, float, float, float, float, float)", referenced from:
      INet::INet() in inet.o
  "gnn::TensorTemplate<gnn::CPU, gnn::DENSE, float>::CopyFrom(gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>&)", referenced from:
      Predict(std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, std::__1::vector<std::__1::vector<double, std::__1::allocator<double> >*, std::__1::allocator<std::__1::vector<double, std::__1::allocator<double> >*> >&) in nn_api.o
  "gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::GetMatMode()", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::GetMatType()", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::Reshape(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >)", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::CopyFrom(gnn::TensorTemplate<gnn::CPU, gnn::CSR_SPARSE, float>&)", referenced from:
      OldQNet::SetupGraphInput(std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, int const*) in old_qnet.o
      QNet::SetupGraphInput(std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, int const*) in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::TensorTemplate()", referenced from:
      OldQNet::OldQNet() in old_qnet.o
      QNet::QNet() in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float>::GetMatMode()", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float> in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float>::GetMatType()", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float> in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float>::Reshape(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >)", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float> in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::GetMatMode()", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in inet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::GetMatType()", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in inet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::Deserialize(__sFILE*)", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in inet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::Reshape(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >)", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in inet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::CopyFrom(gnn::TensorTemplate<gnn::CPU, gnn::DENSE, float>&)", referenced from:
      OldQNet::SetupGraphInput(std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, int const*) in old_qnet.o
      OldQNet::SetupTrain(std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<double, std::__1::allocator<double> >&) in old_qnet.o
      QNet::SetupGraphInput(std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, int const*) in qnet.o
      QNet::SetupTrain(std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<std::__1::shared_ptr<Graph>, std::__1::allocator<std::__1::shared_ptr<Graph> > >&, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >*, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> >*> >&, std::__1::vector<int, std::__1::allocator<int> >&, std::__1::vector<double, std::__1::allocator<double> >&) in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::SetRandN(float, float)", referenced from:
      OldQNet::BuildNet() in old_qnet.o
      QNet::BuildNet() in qnet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::Serialize(__sFILE*)", referenced from:
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
      vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float> in inet.o
  "gnn::TensorTemplate<gnn::GPU, gnn::DENSE, float>::TensorTemplate()", referenced from:
      INet::INet() in inet.o
  "gnn::SubgraphMsgPass<gnn::GPU, float>::InitCPUWeight(gnn::GraphStruct*)", referenced from:
      vtable for gnn::SubgraphMsgPass<gnn::GPU, float> in old_qnet.o
      vtable for gnn::SubgraphMsgPass<gnn::GPU, float> in qnet.o
  "gnn::Edge2NodeMsgPass<gnn::GPU, float>::InitCPUWeight(gnn::GraphStruct*)", referenced from:
      vtable for gnn::Edge2NodeMsgPass<gnn::GPU, float> in old_qnet.o
      vtable for gnn::Edge2NodeMsgPass<gnn::GPU, float> in qnet.o
  "gnn::Node2EdgeMsgPass<gnn::GPU, float>::InitCPUWeight(gnn::GraphStruct*)", referenced from:
      vtable for gnn::Node2EdgeMsgPass<gnn::GPU, float> in qnet.o
  "gnn::Node2NodeMsgPass<gnn::GPU, float>::InitCPUWeight(gnn::GraphStruct*)", referenced from:
      vtable for gnn::Node2NodeMsgPass<gnn::GPU, float> in old_qnet.o
      vtable for gnn::Node2NodeMsgPass<gnn::GPU, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::GetMatType()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::SetRef(void*)", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::AsScalar()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float>::TensorVarTemplate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> > std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> > std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::CSR_SPARSE, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::GetMatType()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::SetRef(void*)", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::AsScalar()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::OnesGrad()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::ZeroGrad()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::TensorVarTemplate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> > std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> > std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
     (maybe you meant: __ZN3gnn17TensorVarTemplateINS_3GPUENS_5DENSEEfEC1ENSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS4_6vectorIiNS8_IiEEEE)
  "gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::TensorVarTemplate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >)", referenced from:
      gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::TensorVarTemplate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >) in old_qnet.o
      gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::TensorVarTemplate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >) in qnet.o
  "gnn::ReLU<gnn::GPU, float>::ReLU(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::ReLU<gnn::GPU, float> > std::__1::shared_ptr<gnn::ReLU<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::ReLU<gnn::GPU, float> > std::__1::shared_ptr<gnn::ReLU<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::MatMul<gnn::GPU, float>::MatMul(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, gnn::Trans, gnn::Trans, gnn::PropErr)", referenced from:
      std::__1::shared_ptr<gnn::MatMul<gnn::GPU, float> > std::__1::shared_ptr<gnn::MatMul<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::MatMul<gnn::GPU, float> > std::__1::shared_ptr<gnn::MatMul<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
  "gnn::IMsgPass<gnn::GPU, float>::Forward(std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, std::__1::vector<std::__1::shared_ptr<gnn::Variable>, std::__1::allocator<std::__1::shared_ptr<gnn::Variable> > >&, gnn::Phase)", referenced from:
      vtable for gnn::Node2NodeMsgPass<gnn::GPU, float> in old_qnet.o
      vtable for gnn::Edge2NodeMsgPass<gnn::GPU, float> in old_qnet.o
      vtable for gnn::SubgraphMsgPass<gnn::GPU, float> in old_qnet.o
      vtable for gnn::Node2NodeMsgPass<gnn::GPU, float> in qnet.o
      vtable for gnn::Edge2NodeMsgPass<gnn::GPU, float> in qnet.o
      vtable for gnn::Node2EdgeMsgPass<gnn::GPU, float> in qnet.o
      vtable for gnn::SubgraphMsgPass<gnn::GPU, float> in qnet.o
      ...
  "gnn::IMsgPass<gnn::GPU, float>::IMsgPass(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool)", referenced from:
      std::__1::shared_ptr<gnn::Node2NodeMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::Node2NodeMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::Edge2NodeMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::Edge2NodeMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::SubgraphMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::SubgraphMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in old_qnet.o
      std::__1::shared_ptr<gnn::Node2NodeMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::Node2NodeMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
      std::__1::shared_ptr<gnn::Edge2NodeMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::Edge2NodeMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
      std::__1::shared_ptr<gnn::Node2EdgeMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::Node2EdgeMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
      std::__1::shared_ptr<gnn::SubgraphMsgPass<gnn::GPU, float> > std::__1::shared_ptr<gnn::SubgraphMsgPass<gnn::GPU, float> >::make_shared<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&&) in qnet.o
      ...
  "gnn::ParamSet<gnn::GPU, float>::DeepCopyFrom(gnn::ParamSet<gnn::GPU, float>&)", referenced from:
      _UpdateSnapshot in tsp2d_lib-d997fd.o
  "gnn::ParamSet<gnn::GPU, float>::Load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      _LoadModel in tsp2d_lib-d997fd.o
  "gnn::ParamSet<gnn::GPU, float>::Save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      _SaveModel in tsp2d_lib-d997fd.o
  "gnn::ParamSet<gnn::GPU, float>::AddParam(std::__1::shared_ptr<gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> >)", referenced from:
      std::__1::shared_ptr<gnn::DTensorVar<gnn::GPU, float> > gnn::add_diff<gnn::DTensorVar, gnn::GPU, float, int>(gnn::ParamSet<gnn::GPU, float>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::initializer_list<int>) in old_qnet.o
      std::__1::shared_ptr<gnn::DTensorVar<gnn::GPU, float> > gnn::add_diff<gnn::DTensorVar, gnn::GPU, float, int>(gnn::ParamSet<gnn::GPU, float>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::initializer_list<int>) in qnet.o
  "gnn::ParamSet<gnn::GPU, float>::ParamSet()", referenced from:
      INet::INet() in inet.o
  "gnn::GpuHandle::Init(int, unsigned int)", referenced from:
      _Init in tsp2d_lib-d997fd.o
  "vtable for gnn::TensorTemplate<gnn::GPU, gnn::DENSE, int>", referenced from:
      gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float>::~TensorTemplate() in old_qnet.o
      gnn::TensorTemplate<gnn::GPU, gnn::ROW_SPARSE, float>::~TensorTemplate() in qnet.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "non-virtual thunk to gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::OnesGrad()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "non-virtual thunk to gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float>::ZeroGrad()", referenced from:
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in old_qnet.o
      vtable for gnn::TensorVarTemplate<gnn::GPU, gnn::DENSE, float> in qnet.o
  "_cudaFree", referenced from:
      void thrust::cuda_cub::free<thrust::cuda_cub::tag, thrust::device_ptr<void> >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::tag>&, thrust::device_ptr<void>) in old_qnet.o
      void thrust::cuda_cub::free<thrust::cuda_cub::tag, thrust::device_ptr<void> >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::tag>&, thrust::device_ptr<void>) in qnet.o
      void thrust::cuda_cub::free<thrust::cuda_cub::tag, thrust::device_ptr<void> >(thrust::cuda_cub::execution_policy<thrust::cuda_cub::tag>&, thrust::device_ptr<void>) in inet.o
  "_cudaGetErrorString", referenced from:
      thrust::system::cuda_cub::detail::cuda_error_category::message(int) const in old_qnet.o
      thrust::system::cuda_cub::detail::cuda_error_category::message(int) const in qnet.o
      thrust::system::cuda_cub::detail::cuda_error_category::message(int) const in inet.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/dll/libtsp2d.so] Error 1

**Comment by Hanjun-Dai** [comment]
Did you build the GPU part of the code? It looks like you built for CPU only but tried to use GPU code.
